env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - react
  - simple-import-sort
rules: {
  "react/react-in-jsx-scope": "off",
  "no-unused-vars": "off",
  "import/no-unresolved": "off",
  "import/extensions": "off",
  "import/no-extraneous-dependencies": "off",
  "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx", ".tsx"] }],
      "import/prefer-default-export": ["warn", { "target": "any" }],
  "simple-import-sort/imports": 'error',
  "simple-import-sort/exports": 'error',
}
ignorePatterns: ['node_modules/', 'dist/']
